let num1=10;
let num2=20;
console.log("before swapping !");
console.log(num1);
console.log(num2);
num1=num1+num2;
num2=num1-num2;
num1=num1-num2;
console.log("after swapping !");
console.log(num1);
console.log(num2);
